config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  root to: 'snippets#index'
  get 'archives', to: 'snippets#archives', as: 'archives' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/snippet.rb
class Snippet < ApplicationRecord
  CATEGORIES = ["Ruby", "JavaScript", "CSS"]

  has_many :snippet_tags, dependent: :destroy
  has_many :tags, through: :snippet_tags
  validates :title, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/snippet_tag.rb
class SnippetTag < ApplicationRecord
  belongs_to :snippet
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  def index
    @snippets = Snippet.where(archived: false)
  end

  def archives
    @snippets = Snippet.where(archived: true)
  end

  def show
  end

  def new
    @snippet = Snippet.new
  end

  def edit
  end

  def create
    @snippet = Snippet.new(snippet_params)
    if @snippet.save
      redirect_to snippet_path(@snippet)
    else
      render :new
    end
  end

  def update
    @snippet.update(snippet_params)
    redirect_to snippet_path(@snippet)
  end

  def destroy
    @snippet.destroy
    redirect_to snippets_path
  end
  
  private
  def set_snippet
    @snippet = Snippet.find(params[:id])
  end
  
  def snippet_params
    params.require(:snippet).permit(:title, :code, :category, :archived, tag_ids: [])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails CSS Checkboxes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="data:image/x-icon;" type="image/x-icon">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body id="<%= params[:controller] %>_<%= params[:action] %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <main class="container">
      <div class="row">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/show.html.erb
<div class="form-post">
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>
  <p>
  <% @post.tags.each do |tag| %>
    <span class="tag <%= tag.style %>"><%= tag.name %></span>
  <% end %>
  </p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon">
  <h1>&lt;&#47;Snippets&gt;</h1>
    <ul class="navbar-nav">
      <li class="nav-item index">
        <%= link_to "/", class: "nav-link" do %>
          <%= image_tag("list.svg") %>
        <% end %>
      </li>
      <li class="nav-item archives">
        <%= link_to archives_path, class: "nav-link" do %>
          <%= image_tag("archives.svg") %>
        <% end %>
      </li>
      <li class="nav-item new">
        <%= link_to new_snippet_path, class: "nav-link" do %>
          <%= image_tag("new.svg") %>
        <% end %>
      </li>
    </ul>
</div>

app/views/snippets/_form.html.erb
<div class="col-xs-12 col-md-6 offset-md-3 card">
  <%= simple_form_for(snippet) do |f| %>
    <%= f.input :title %>
    <%= f.input :category,
                as: :radio_buttons,
                collection_wrapper_tag: "div",
                collection_wrapper_class: 'category-wrapper',
                item_wrapper_class: 'category-item',
                input_html: {class: 'category-selector'},
                collection: Snippet::CATEGORIES %>
    <%= f.input :code %>
    <%= f.association :tags, as: :check_boxes, input_html: { class: "tag-selector" }, item_wrapper_class: 'tag-item' %>
    <%= f.input :archived, input_html: { class: "toggle" } %>
    <%= f.submit "Save", class: " "  %>
  <% end %>
</div>

app/views/snippets/_snippet.html.erb
<div class="col-sm-12 col-md-6 offset-md-3 card <%= snippet.category.downcase %> <%= state ||= '' %> <%= "archived" if snippet.archived %> <%= closed ||= '' %>">
  <div class="tools">
    <%= link_to "", edit_snippet_path(snippet), class:"edit" %>
    <%= link_to "",
                  snippet_path(snippet),
                  method: :delete,
                  class: 'delete',
                  data: { confirm: "Are you sure?" } %>
  </div>
  <h2><%= snippet.title %></h2>
  <pre><code><%= snippet.code %></code></pre>
  <%= link_to snippet_path(snippet) do %>
    <button aria-label="Show" class="show-btn"></button>
  <% end %>
  <p><%= render partial: 'tag', collection: snippet.tags %></p>
</div>

app/views/snippets/_tag.html.erb
<span class="tag"><%= tag.name %></span>

app/views/snippets/archives.html.erb
<%= render @snippets, state: 'preview' ,closed: 'closed' %>

app/views/snippets/edit.html.erb
<%= render 'form', snippet: @snippet %>

app/views/snippets/index.html.erb
<%= render @snippets, closed: 'closed' %>

app/views/snippets/new.html.erb
<%= render 'form', snippet: @snippet %>

app/views/snippets/show.html.erb
<%= render @snippet %>